### ISSUE TITLE
[BUG]tx_sfeventmgt_related_events doesn't exist in table

### ISSUE THREAD

**Issue by Tobias-Gl** [derhansen/sf_event_mgt_contentelements#5]
After installing the extension, the error message "Error: Key column 'tx_sfeventmgt_related_events' doesn't exist in table" was displayed.

Analyze Database Structure
CREATE INDEX 'index_eventcontent' on 'tt_content' (tx_sfeventmgt_related_events)

Typo3: 11.5.27
sf_event_mgt: 6.4.1
sf-event-mgt-contentelements: 1.0.0

**Comment by derhansen** [comment]
Thanks for your report. The index key was wrong. This has been fixed in version 1.0.1 and 2.0.1, which hast been published today.
